name: notes_app
description: "A simple Flutter Notes application."
publish_to: 'none' # This prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0" # Ensure compatibility with Flutter SDK versions

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5 # For state management
  shared_preferences: ^2.1.0 # To store notes locally
  cupertino_icons: ^1.0.8 # iOS style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #assets:
    #- assets/icons/ # Example: Add icons or images here (folder must exist)
    #- assets/images/ # Example: Store images used in the app
